#Google Analytics
analytics-id: G-FKPL7Q39KJ

#Subtitle
subtitle:
  active: true
  # text: â¤ï¸ ğŸ§¡ ğŸ’› ğŸ’š ğŸ’™ ğŸ’œ ğŸ–¤

#Nav 
nav:
  pages:
    active: true
  social:
    active: true

#Featured images in homepage
featured-img:
  active: true

#Show categories at the end of posts
categories:
  active: true

#Show date and read time under the post title
date-under-post:
  active: true

#Use MathJAX
mathjax:
  active: true

#Show related posts based on categories
related-posts:
  active: true
  title: "You May Also Enjoy"

#Comments
comments: true